# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.cache/wt [current_project]
set_property parent.project_path D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/sevenseg_dec.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/divider.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/display_sel.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/decoder3_8.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/Counter.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/circuit/Operation_Control_Unit.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/circuit/Control_Signals.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/arithmetic/Shifter.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/memory/Rom.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/memory/Register.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/memory/Regifile.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/memory/Ram.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/plexers/Multiplexer_8.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/plexers/Multiplexer_4.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/plexers/Multiplexer_2.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/FPGADigit.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/divider_pc.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/arithmetic/Comparator.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/wiring/Bit_Extender_32_Sign.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/circuit/ALU.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/arithmetic/Adder.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/circuit/Hard_Wired_Controller.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/io/Counter_pc.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/circuit/Single_Cycle_RISCV.v
  D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/top/cpu.v
}
read_xdc D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/constrs_1/imports/constr/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/pro/principles_of_computer_composition/cpu24-riscv/Single_Cycle_RISCV2/single_cycle_cpu/single_cycle_cpu.srcs/constrs_1/imports/constr/Nexys4DDR_Master.xdc]

synth_design -top cpu -part xc7a100tcsg324-1
write_checkpoint -noxdef cpu.dcp
catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
